# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-20 05:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poke_app', '0003_auto_20171219_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='poke_history',
        ),
    ]
